# Generated by Django 2.0.4 on 2018-04-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desciption', models.TextField(max_length=1000)),
                ('slug', models.SlugField(max_length=40)),
                ('time', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
                ('details', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='films.Detail')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='casts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Cast'),
        ),
        migrations.AddField(
            model_name='detail',
            name='directors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Director'),
        ),
        migrations.AddField(
            model_name='detail',
            name='episodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Episode'),
        ),
        migrations.AddField(
            model_name='detail',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Genres'),
        ),
        migrations.AddField(
            model_name='detail',
            name='writers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Writer'),
        ),
    ]
