# Generated by Django 2.0.4 on 2018-04-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='time',
        ),
    ]
