# Generated by Django 2.0.4 on 2018-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaion',
            name='region',
            field=models.IntegerField(choices=[(1, 'Asia'), (3, 'America'), (4, 'Africa'), (5, 'Australia'), (6, 'Antarctica'), (7, 'North America'), (8, 'South America')], default=1),
        ),
    ]
