# Generated by Django 2.0.4 on 2018-04-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_episode_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='disable',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Hide Genres'),
        ),
    ]
