# Generated by Django 2.0.4 on 2018-04-20 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20180421_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='cast',
            name='sex',
            field=models.BooleanField(default=False, help_text='The casr is male You cant click it', verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='director',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='director',
            name='sex',
            field=models.BooleanField(default=False, help_text='The casr is male You cant click it', verbose_name='Sex'),
        ),
    ]
