# Generated by Django 2.0.4 on 2018-04-20 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20180421_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='titleImage',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000, verbose_name='URL Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='titleImage',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000, verbose_name='URL Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='writer',
            name='sex',
            field=models.BooleanField(default=False, help_text='The casr is male You cant click it', verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='writer',
            name='titleImage',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000, verbose_name='URL Image'),
            preserve_default=False,
        ),
    ]
