# Generated by Django 2.0.4 on 2018-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20180420_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='genres',
        ),
        migrations.AddField(
            model_name='detail',
            name='genres',
            field=models.ManyToManyField(to='films.Genres', verbose_name='genres'),
        ),
    ]
