# Generated by Django 2.0.4 on 2018-04-20 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20180420_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='detail',
        ),
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='detail',
            name='casts',
        ),
        migrations.AddField(
            model_name='detail',
            name='casts',
            field=models.ManyToManyField(to='films.Cast', verbose_name='Cast'),
        ),
        migrations.RemoveField(
            model_name='detail',
            name='directors',
        ),
        migrations.AddField(
            model_name='detail',
            name='directors',
            field=models.ManyToManyField(to='films.Director', verbose_name='Director'),
        ),
        migrations.RemoveField(
            model_name='detail',
            name='episodes',
        ),
        migrations.AddField(
            model_name='detail',
            name='episodes',
            field=models.ManyToManyField(to='films.Episode', verbose_name='Episode'),
        ),
        migrations.RemoveField(
            model_name='detail',
            name='writers',
        ),
        migrations.AddField(
            model_name='detail',
            name='writers',
            field=models.ManyToManyField(to='films.Writer', verbose_name='Writer'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
