# Generated by Django 2.0.4 on 2018-04-20 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20180420_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='detail',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='detail',
            name='watchDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date puslish'),
        ),
    ]
