# Generated by Django 2.0.4 on 2018-04-20 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20180420_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='background',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='hot',
            field=models.BooleanField(default=False, help_text='The movie is Good/normal If checked is good.', verbose_name='Is hot'),
        ),
        migrations.AddField(
            model_name='detail',
            name='status',
            field=models.BooleanField(default=False, help_text='The movie hide/show You cant click it', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='detail',
            name='titleImage',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='urlData',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='background',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='urlData',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
