# Generated by Django 2.0.4 on 2018-04-20 02:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('films', '0008_auto_20180420_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ('content_type__app_label', 'content_type__model', 'codename'), 'verbose_name': 'Genres', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelManagers(
            name='genres',
            managers=[
                ('objects', films.models.GenresManager()),
            ],
        ),
        migrations.AddField(
            model_name='genres',
            name='codename',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='codename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genres',
            name='content_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='genres',
            unique_together={('content_type', 'codename')},
        ),
    ]
