# Generated by Django 2.0.4 on 2018-04-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20180420_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genres', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterUniqueTogether(
            name='genres',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='genres',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='content_type',
        ),
    ]
