# Generated by Django 2.0.4 on 2018-04-20 02:34

from django.db import migrations
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20180420_0913'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cast',
            managers=[
                ('objects', films.models.CastManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='director',
            managers=[
                ('objects', films.models.DirectorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='episode',
            managers=[
                ('objects', films.models.EpisodeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='writer',
            managers=[
                ('objects', films.models.WriterManager()),
            ],
        ),
    ]
