# Generated by Django 2.0.4 on 2018-04-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20180420_0934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cast',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='director',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='episode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='writer',
            managers=[
            ],
        ),
    ]
