# Generated by Django 2.0.4 on 2018-04-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20180420_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='directors',
            field=models.ManyToManyField(help_text='Film dorector, click text to add list here ', to='films.Director', verbose_name='Director'),
        ),
    ]
